### ISSUE TITLE
nwpu训练出错

### ISSUE THREAD

**Issue by ljc108** [wfs123456/JCTnet#4]
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/autodl-tmp/JCTnet-main/datasets/crowd.py", line 201, in __getitem__
    dot_map = Image.open(dot_path)
  File "/root/miniconda3/lib/python3.8/site-packages/PIL/Image.py", line 2968, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/root/autodl-tmp/NWPU-Train-Val-Test/train/0908.png'

你好请问我训练nwpu时出这个是什么情况

**Comment by wfs123456** [comment]
这不很明显的报错嘛，0908.png找不到



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月25日(周六) 下午2:40
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wfs123456/JCTnet] nwpu训练出错 (Issue #4)




 
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
 Original Traceback (most recent call last):
 File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
 data = fetcher.fetch(index)
 File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
 data = [self.dataset[idx] for idx in possibly_batched_index]
 File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in 
 data = [self.dataset[idx] for idx in possibly_batched_index]
 File "/root/autodl-tmp/JCTnet-main/datasets/crowd.py", line 201, in getitem
 dot_map = Image.open(dot_path)
 File "/root/miniconda3/lib/python3.8/site-packages/PIL/Image.py", line 2968, in open
 fp = builtins.open(filename, "rb")
 FileNotFoundError: [Errno 2] No such file or directory: '/root/autodl-tmp/NWPU-Train-Val-Test/train/0908.png'
 
你好请问我训练nwpu时出这个是什么情况

**Comment by ljc108** [comment]
> 这不很明显的报错嘛，0908.png找不到
> 
> 
> 
> ---原始邮件---
> 发件人: ***@***.***&gt;
> 发送时间: 2023年3月25日(周六) 下午2:40
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.***&gt;;
> 主题: [wfs123456/JCTnet] nwpu训练出错 (Issue #4)
> 
> 
> 
> 
>  
> FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
>  Original Traceback (most recent call last):
>  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
>  data = fetcher.fetch(index)
>  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
>  data = [self.dataset[idx] for idx in possibly_batched_index]
>  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in 
>  data = [self.dataset[idx] for idx in possibly_batched_index]
>  File "/root/autodl-tmp/JCTnet-main/datasets/crowd.py", line 201, in getitem
>  dot_map = Image.open(dot_path)
>  File "/root/miniconda3/lib/python3.8/site-packages/PIL/Image.py", line 2968, in open
>  fp = builtins.open(filename, "rb")
>  FileNotFoundError: [Errno 2] No such file or directory: '/root/autodl-tmp/NWPU-Train-Val-Test/train/0908.png'
>  
> 你好请问我训练nwpu时出这个是什么情况
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

但是nwpu预处理好后 并没有png格式图片

**Comment by ljc108** [comment]
想问下大佬 qnrf和nwpu大概在多少个epoch后最优
